---
# Manage zsh plugins

- name: Clone zsh-autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ dotfiles_shell_plugins }}/zsh-autosuggestions"
    depth: 1
    update: yes

- name: Clone zsh-syntax-highlighting
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "{{ dotfiles_shell_plugins }}/zsh-syntax-highlighting"
    depth: 1
    update: yes